# Generated by Django 3.1.5 on 2021-01-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rpguser',
            options={'verbose_name': 'RpgUser'},
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='Teste', max_length=255),
            preserve_default=False,
        ),
    ]
