# Generated by Django 3.1.5 on 2021-01-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210122_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='uuid',
            field=models.UUIDField(auto_created=True, default='76937da9-8f83-4ec2-a525-34e54d6c4d42', unique=True),
            preserve_default=False,
        ),
    ]
