# Generated by Django 3.1.5 on 2021-01-22 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='uuid',
        ),
    ]
