# Generated by Django 3.1.5 on 2021-01-24 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_room_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=[])),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='player_details',
        ),
        migrations.AddField(
            model_name='room',
            name='room_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.template'),
        ),
    ]
