# Generated by Django 3.1.5 on 2021-01-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210124_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
